name: 🔂 Surge PR Preview

on: 
    pull_request:
    push:
        branches: [testing]

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # allow surge-preview to create/update PR comments
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'pnpm'
          cache-dependency-path: example/pnpm-lock.yaml
      - name: Install dependencies and Build
        run: | 
          cd example
          mv astro.config.preview.mjs astro.config.mjs
          pnpm install
          pnpm build
      - uses: afc163/surge-preview@v1
        id: preview_step
        with:
          github_token: ${{ github.token }}
          surge_token: ${{ secrets.SURGE_TOKEN }}
          dist: example/dist
          teardown: true
          failOnError: true
          build: |
            bash -c "echo Done"
      - name: Get the preview_url
        run: echo "url => ${{ steps.preview_step.outputs.preview_url }}"